### PR TITLE
added SAMP coord broadcast to crossmatch detail

### PR DESCRIPTION
**Pull request by marxide**
Added a new panel to the crossmatch detail template to connect to a SAMP hub running on the user's machine and broadcast coordinates to all connected SAMP clients.

### CODE REVIEW

**Comment by ajstewart** [comment]
Looks good, I shall merge once I've pushed my own half-complete commit onto this branch.

**Comment by ajstewart** [comment]
@marxide you tested this on a local deployment right? I wonder if the website is hosted on ada will it still connect to the users machine on the network?

**Comment by marxide** [comment]
Yes, tested on a local deployment only. I think it should work deployed on ada; the SAMP stuff opens a connection to localhost by default and since this is all within Javascript running in the browser, that should point to the user's machine, not ada.

However, I did encounter problems with CORS during testing and needed to get around that with a browser plugin to temporarily allow CORS. In my experience, this workaround is only needed when testing without a properly configured webserver (e.g. the Django test server invoke with `manage.py runserver`). I suspect it should be fine on ada, but if not we can debug from there. I don't expect the SAMP stuff failing for work correctly to break anything else on the page.

**Comment by ajstewart** [comment]
Tested on ada - works well 👍 (at least on my setup!).

**Comment by ajstewart** [comment]
Is it normal behaviour that `reset connection` opens the connection request window in Aladin, but then selecting `broadcast coordinates` also opens the connection request? On the third click it will then go through and snap Aladain.

**Pull request merged**
